// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVmzFWGgFf5Mh9uwpyV1MHsKWT40hO_PQ',
    appId: '1:1000685570084:web:87cdc0491dc43d5019b0b1',
    messagingSenderId: '1000685570084',
    projectId: 'unics-e46a4',
    authDomain: 'unics-e46a4.firebaseapp.com',
    storageBucket: 'unics-e46a4.appspot.com',
    measurementId: 'G-G4QH52F4DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtJyVEkgVdI4SFHI-cJHe63Sdp43va-x0',
    appId: '1:1000685570084:android:523dddb00fe08ab819b0b1',
    messagingSenderId: '1000685570084',
    projectId: 'unics-e46a4',
    storageBucket: 'unics-e46a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC7KSivgOMgB14xMUvUnhHvpC5YZlGIaY',
    appId: '1:1000685570084:ios:3c0df088057ee0e819b0b1',
    messagingSenderId: '1000685570084',
    projectId: 'unics-e46a4',
    storageBucket: 'unics-e46a4.appspot.com',
    androidClientId: '1000685570084-45ufkleqbrhmpfj9jcriqrgdidvvcvep.apps.googleusercontent.com',
    iosClientId: '1000685570084-p00rn9tpdigj6nsknn0n6rb785u7dr0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.unicecMobi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC7KSivgOMgB14xMUvUnhHvpC5YZlGIaY',
    appId: '1:1000685570084:ios:3c0df088057ee0e819b0b1',
    messagingSenderId: '1000685570084',
    projectId: 'unics-e46a4',
    storageBucket: 'unics-e46a4.appspot.com',
    androidClientId: '1000685570084-45ufkleqbrhmpfj9jcriqrgdidvvcvep.apps.googleusercontent.com',
    iosClientId: '1000685570084-p00rn9tpdigj6nsknn0n6rb785u7dr0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.unicecMobi',
  );
}
